config firewall address
    edit "IOC_c2_demo_invalid"
        set type fqdn
        set fqdn "c2-demo.invalid"
        set comment "Block request INC-12345"
    next
    edit "IOC_malicious_example_invalid"
        set type fqdn
        set fqdn "malicious-example.invalid"
        set comment "Block request INC-12345"
    next
    edit "IOC_198_51_100_25"
        set comment "Block request INC-12345"
        set subnet 198.51.100.25 255.255.255.255
    next
    edit "IOC_203_0_113_0_28"
        set comment "Block request INC-12345"
        set subnet 203.0.113.0 255.255.255.240
    next
end

config firewall addrgrp
    edit "GRP_IOC_inc_12345"
        set member "IOC_c2_demo_invalid" "IOC_malicious_example_invalid" "IOC_198_51_100_25" "IOC_203_0_113_0_28"
        set comment "CHG-67890"
    next

    edit "GRP_BLOCK_IOC"
        append member "GRP_IOC_inc_12345"
    next
end
